baseURL = "http://code0.ninja/"
title = "Code Template Ninja"
theme = "learn"

[params]
  editURL = "https://github.com/briancsparks/code0-ninja-prosper/edit/master/content/"
  disableNextPrev = true

[outputs]
home = ["HTML", "RSS", "JSON"]
